#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'docs', 'generated');
const checkOnly = process.argv.includes('--check');

const rel = (p) => path.relative(root, p).replaceAll(path.sep, '/');
const read = (p) => fs.readFile(path.join(root, p), 'utf8');

async function exists(p) {
  try {
    await fs.access(path.join(root, p));
    return true;
  } catch {
    return false;
  }
}

async function walk(dir, predicate = () => true) {
  const abs = path.join(root, dir);
  const out = [];
  async function visit(current) {
    const entries = await fs.readdir(current, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name === 'node_modules' || entry.name === '.git') continue;
      const p = path.join(current, entry.name);
      if (entry.isDirectory()) {
        await visit(p);
      } else if (predicate(p)) {
        out.push(p);
      }
    }
  }
  if (await exists(dir)) await visit(abs);
  return out.sort((a, b) => rel(a).localeCompare(rel(b)));
}

function header(title) {
  return `# ${title}\n\n_Generated by \`scripts/generate_agent_context.mjs\`._\n\n`;
}

function cleanDescription(raw) {
  if (!raw) return '-';
  return raw
    .replace(/[`'"]/g, '')
    .replace(/\s*\+\s*/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\|/g, '\\|') || '-';
}

function compactList(items) {
  return items.length ? items.map((x) => `\`${x}\``).join('<br>') : '-';
}

async function commandIndex() {
  const cli = await read('src/cli.ts');
  const re =
    /(?:(?:const\s+([A-Za-z0-9_]+)\s*=\s*)?([A-Za-z0-9_]+)\s*\n\s*\.command\('([^']+)'\))/g;
  const matches = [...cli.matchAll(re)];
  const varToCommand = new Map();
  const rows = [];

  for (let i = 0; i < matches.length; i++) {
    const m = matches[i];
    const assignedVar = m[1];
    const receiver = m[2];
    const command = m[3];
    const start = m.index ?? 0;
    const end = matches[i + 1]?.index ?? cli.length;
    const block = cli.slice(start, end);
    const parent = receiver === 'program' ? '' : varToCommand.get(receiver) ?? receiver;
    const full = parent ? `${parent} ${command}` : command;
    if (assignedVar) varToCommand.set(assignedVar, full);

    const descRaw = block.match(/\.description\(([\s\S]*?)\)\s*(?:\.|\n)/)?.[1];
    const args = [...block.matchAll(/\.argument\(\s*(['"`])([^'"`]+)\1/g)].map(
      (x) => x[2],
    );
    const opts = [
      ...block.matchAll(/\.(?:requiredOption|option)\(\s*(['"`])([^'"`]+)\1/g),
    ].map((x) => x[2]);
    const source = block.match(/import\('\.\/commands\/([^']+)\.js'\)/)?.[1];
    rows.push({
      command: full,
      source: source ? `src/commands/${source}.ts` : '-',
      args,
      opts,
      description: cleanDescription(descRaw),
    });
  }

  let out = header('Command Index');
  out += '| Command | Source | Arguments | Options | Description |\n';
  out += '|---|---|---|---|---|\n';
  for (const row of rows) {
    out += `| \`${row.command}\` | ${row.source === '-' ? '-' : `\`${row.source}\``} | ${compactList(
      row.args,
    )} | ${compactList(row.opts)} | ${row.description} |\n`;
  }
  return out;
}

async function moduleMap() {
  const files = await walk('src', (p) => p.endsWith('.ts'));
  const tests = await walk('tests', (p) => p.endsWith('.test.ts') || p.endsWith('.spec.ts'));
  const dirs = new Map();
  for (const file of files) {
    const r = rel(file);
    const parts = r.split('/');
    const dir = parts.length > 2 ? `${parts[0]}/${parts[1]}` : parts[0];
    const entry = dirs.get(dir) ?? { files: 0, tests: 0, notes: '-' };
    entry.files++;
    dirs.set(dir, entry);
  }
  for (const file of tests) {
    const content = await fs.readFile(file, 'utf8');
    const target = content.match(/from ['"]\.\.\/src\/([^/'"]+)/)?.[1];
    if (target) {
      const key = `src/${target}`;
      const entry = dirs.get(key) ?? { files: 0, tests: 0, notes: '-' };
      entry.tests++;
      dirs.set(key, entry);
    }
  }

  const notes = {
    'src/commands': 'command executors and renderers',
    'src/session': 'browser/session automation helpers',
    'src/daemon': 'background daemon client/server/protocol',
    'src/io': 'output, prompts, and errors',
    'src/auth': 'login/session/cookie helpers',
    'src/util': 'shared utilities',
  };

  let out = header('Module Map');
  out += '| Directory | Source Files | Related Tests | Notes |\n';
  out += '|---|---:|---:|---|\n';
  for (const dir of [...dirs.keys()].sort()) {
    const entry = dirs.get(dir);
    out += `| \`${dir}\` | ${entry.files} | ${entry.tests} | ${notes[dir] ?? entry.notes} |\n`;
  }
  return out;
}

async function testIndex() {
  const tests = await walk('tests', (p) => p.endsWith('.test.ts') || p.endsWith('.spec.ts'));
  let out = header('Test Index');
  out += '| Test File | Focus | Risk Notes |\n';
  out += '|---|---|---|\n';
  for (const file of tests) {
    const content = await fs.readFile(file, 'utf8');
    const name = path.basename(file).replace(/\.(test|spec)\.ts$/, '');
    const risks = [];
    if (/live|doctor-live|process\.env|BB1688|1688\s/.test(content + name))
      risks.push('live/session-sensitive');
    if (/playwright|BrowserContext|Page|page-state|risk-control/i.test(content))
      risks.push('browser/page-state');
    if (/fixture|jsonp|mtop|capture/i.test(content)) risks.push('fixture/parser');
    out += `| \`${rel(file)}\` | ${name} | ${risks.join(', ') || '-'} |\n`;
  }
  return out;
}

function extractInterfaces(source, file) {
  const lines = source.split('\n');
  const interfaces = [];
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^export interface ([A-Za-z0-9_]+)/);
    if (!m) continue;
    const name = m[1];
    const keep =
      /(Args|Opts|Result|Offer|Message|CartItem|Order|Sku|Price|Attribute|Package)/.test(
        name,
      );
    if (!keep) continue;

    const body = [];
    let depth = 0;
    for (let j = i; j < lines.length; j++) {
      const line = lines[j];
      if (j > i) body.push(line);
      depth += (line.match(/\{/g) ?? []).length;
      depth -= (line.match(/\}/g) ?? []).length;
      if (j > i && depth <= 0) break;
    }
    const fields = body
      .map((line) => line.trim())
      .filter((line) => /^[A-Za-z0-9_?]+:/.test(line) || /^\/\*\*/.test(line))
      .slice(0, 14)
      .map((line) => line.replace(/\|/g, '\\|'));
    interfaces.push({ name, file, fields });
  }
  return interfaces;
}

async function jsonShapes() {
  const files = await walk('src', (p) => p.endsWith('.ts'));
  const interfaces = [];
  for (const file of files) {
    const source = await fs.readFile(file, 'utf8');
    interfaces.push(...extractInterfaces(source, rel(file)));
  }

  let out = header('JSON Shapes');
  out +=
    'This is a heuristic index of exported TypeScript interfaces that are likely to matter for agent-facing JSON.\n\n';
  out += '| Interface | File | Notable Fields |\n';
  out += '|---|---|---|\n';
  for (const it of interfaces.sort((a, b) => a.file.localeCompare(b.file) || a.name.localeCompare(b.name))) {
    out += `| \`${it.name}\` | \`${it.file}\` | ${it.fields.length ? it.fields.map((x) => `\`${x}\``).join('<br>') : '-'} |\n`;
  }
  return out;
}

const outputs = new Map([
  ['command-index.md', await commandIndex()],
  ['module-map.md', await moduleMap()],
  ['test-index.md', await testIndex()],
  ['json-shapes.md', await jsonShapes()],
]);

if (checkOnly) {
  const mismatches = [];
  for (const [name, content] of outputs) {
    const target = path.join(outDir, name);
    let current = '';
    try {
      current = await fs.readFile(target, 'utf8');
    } catch {
      mismatches.push(name);
      continue;
    }
    if (current !== content) mismatches.push(name);
  }
  if (mismatches.length) {
    console.error(
      `Generated agent context is stale: ${mismatches.join(', ')}. Run pnpm agent-context.`,
    );
    process.exit(1);
  }
  console.log('Generated agent context is fresh.');
} else {
  await fs.mkdir(outDir, { recursive: true });
  for (const [name, content] of outputs) {
    await fs.writeFile(path.join(outDir, name), content);
  }
  console.log(`Generated agent context files in ${rel(outDir)}`);
}

